# Generated by Django 4.0.1 on 2022-11-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, verbose_name='username')),
                ('image', models.ImageField(upload_to='', verbose_name='img')),
            ],
        ),
    ]
