# Generated by Django 4.0.1 on 2022-11-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_uploadimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
